name: deploy to pm2 server (pnpm + wasm)

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout source
        uses: actions/checkout@v3

      - name: set up rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: install wasm-pack
        run: cargo install wasm-pack

      - name: set up node + pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: install dependencies and build frontend
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      - name: verify build output
        run: ls -la dist/

      - name: upload build to server via scp
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "dist/*"
          target: "~/docloop"
          timeout: 60s
          command_timeout: 15m

      - name: reload or start pm2 process via ssh
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/docloop
            pm2 reload ${{ secrets.PM2_PROCESS }} || pm2 start "npx serve -s ." --name "${{ secrets.PM2_PROCESS }}"
